"""Change Primary key on Cog

Revision ID: 8b014ce02b6f
Revises: 005088ed4feb
Create Date: 2025-07-30 16:34:21.485826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b014ce02b6f'
down_revision: Union[str, Sequence[str], None] = '005088ed4feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cogs', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cogs', sa.Column('identifier', sa.BIGINT(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
