"""Initial migration

Revision ID: 005088ed4feb
Revises: 
Create Date: 2025-07-24 22:34:08.652094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005088ed4feb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cogs',
    sa.Column('identifier', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('users',
    sa.Column('identifier', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('daily',
    sa.Column('identifier', sa.BigInteger(), nullable=False),
    sa.Column('last_daily', sa.Date(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['users.identifier'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('money',
    sa.Column('identifier', sa.BigInteger(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['users.identifier'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('robbing',
    sa.Column('identifier', sa.BigInteger(), nullable=False),
    sa.Column('next_robbing', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['users.identifier'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robbing')
    op.drop_table('money')
    op.drop_table('daily')
    op.drop_table('users')
    op.drop_table('cogs')
    # ### end Alembic commands ###
